export const ALL_RENT_REQUEST = 'ALL_RENT_REQUEST';
export const ALL_RENT_SUCCESS = 'ALL_RENT_SUCCESS';
export const ALL_RENT_FAIL = 'ALL_RENT_FAIL';

export const ALL_RENT_REQUEST_HOME = 'ALL_RENT_REQUEST_HOME';
export const ALL_RENT_SUCCESS_HOME = 'ALL_RENT_SUCCESS_HOME';
export const ALL_RENT_FAIL_HOME = 'ALL_RENT_FAIL_HOME';

export const RENT_DETAILS_REQUEST = 'RENT_DETAILS_REQUEST';
export const RENT_DETAILS_SUCCESS = 'RENT_DETAILS_SUCCESS';
export const RENT_DETAILS_FAIL = 'RENT_DETAILS_FAIL';

export const RENT_SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
